config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    get 'confirm_email', to: 'users/registrations#confirm_email'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'homes#top'

  resources :users, except: [:new, :create] do
    member do
      get :following, :followers, :likes
    end
  end

  get 'users/:id/unsubscribe', to: 'users#unsubscribe', as: 'confirm_unsubscribe'

  resources :posts do
    collection do
      get :rank
    end
    resources :photos, only: [:create]
    resources :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :contacts, only: [:new, :create] do
    collection do
      get 'confirm', to: 'contacts#error'
      post 'confirm'
      get 'back', to: 'contacts#error'
      post 'back'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 100 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post

  attachment :image

  validates :image, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  # いいねランキング用
  has_many :liked_users, through: :likes, source: :user
  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_attachments_for :photos, attachment: :image
  validates :title, presence: true
  validates :caption, presence: true, length: { maximum: 1000 }
  validates :photos_images, presence: true, length: { maximum: 5, too_long: "は最大%{count}枚まで投稿できます" }

  def liked_by(user)
    # user_idとpost_idが一致するlikeを検索する
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  # いいねランキング用
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  def follow(other_user)
    unless self == other_user
      relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def following(other_user)
    relationships.find_by(follow_id: other_user.id)
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: 'guest') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable, :recoverable,
          :trackable, :rememberable, :validatable, :confirmable

  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 10 }

  validates :profile, length: { maximum: 1000 }

  attachment :profile_image
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :non_presence_chat, except: [:create]

  def show
    @user = User.find_by(id: params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    if user_rooms.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    else
      @room = user_rooms.room
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
    redirect_to request.referer
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

  def non_presence_chat
    @user = User.find_by(id: params[:id])
    if @user.blank?
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @posts = Post.all.order('created_at DESC').limit(3)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def index
    @post_for_likes = Like.where(post_id: params[:post_id])
    @post = Post.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    like = current_user.likes.new(post_id: @post.id)
    like.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :non_presence_post, except: [:new, :create, :index, :rank]

  def new
    @post = Post.new
    @post.photos.build
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
      flash[:notice] = "投稿が保存されました。"
    else
      render 'new'
    end
  end

  def index
    @search = Post.ransack(params[:q])
    @posts = @search.result.page(params[:page]).reverse_order.per(12)
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
    @user = @post.user
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to post_path(@post), alert: "不正なアクセスです。"
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "投稿内容を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if @post.user == current_user
      @post.destroy
      flash[:notice] = "投稿が削除されました。"
    else
      flash[:alert] = "投稿の削除に失敗しました。"
    end
    redirect_to posts_path
  end

  def rank
    posts = Post.includes(:liked_users).sort { |a, b| b.liked_users.size <=> a.liked_users.size }
    @posts = Kaminari.paginate_array(posts).page(params[:page]).per(12)
  end

  private

  def post_params
    params.require(:post).permit(:title, :caption, photos_images: []).merge(user_id: current_user.id)
  end

  def non_presence_post
    @post = Post.find_by(id: params[:id])
    if @post.blank?
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/show.html.erb
<div class="topic">
  <div class="container">
    <h1 class="topic-font my-4"><%= @user.name %>さんとのチャットルーム</h1>
  </div>
</div>

<div class="chat">
  <div class="card chat-card">
      <div class="text-center mt-3">
        <%= form_with model: @chat do |f| %>
          <div class="form-inline justify-content-center mb-2">
            <div class="input-group">
              <%= f.text_field :message, placeholder: "メッセージを入力", class: "form-control w-50 py-3" %>
              <%= f.hidden_field :room_id %>
              <span class="input-group-btn">
                <%= f.submit "送信", class: "btn btn-success" %>
              </span>
            </div>
          </div>
        <% end %>
      </div>

      <div id="chats">
        <% @chats.each do |chat| %>
          <% if chat.user == current_user %>
            <div class="mycomment d-flex justify-content-end py-1">
              <%= chat.message %>
            </div>
          <%else%>
            <div class="pb-1">
              <%= attachment_image_tag chat.user, :profile_image, fallback: "no-image.jpg", class: "profile_image_icon" %>
              <%= chat.message %>
            </div>
          <% end %>
        <% end %>
      </div>
  </div>
</div>

app/views/likes/_like-btn.html.erb
  <% if post.liked_by(current_user).present? %>
    <%= link_to post.likes.count, post_like_path(post.id, post.liked_by(current_user)), method: :delete, remote: true, class: "fas fa-heart heart_red no-underline_heart" %>
  <% else %>
    <%= link_to post.likes.count, post_likes_path(post), method: :post, remote: true, class: "fas fa-heart heart_gray no-underline_heart" %>
  <% end %>

app/views/likes/create.js.erb
$(".like-btn_<%= @post.id %>").html("<%= j(render 'likes/like-btn', post: @post) %>");

app/views/likes/destroy.js.erb
$(".like-btn_<%= @post.id %>").html("<%= j(render 'likes/like-btn', post: @post) %>");

app/views/likes/index.html.erb
<div class="topic">
  <div class="container">
    <h1 class="topic-font my-4">いいね一覧</h1>
  </div>
</div>
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 mx-auto text-center">
      <% if @post.likes.present? %>
        <table class="table">
          <tr>
            <th>いいね数：<%= @post.likes.count %></th>
            <th>会員名</th>
            <th>フォロー</th>
          </tr>
            <% @post_for_likes.each do |like| %>
              <tr>
                <td class="pt-3">
                  <%= link_to user_path(like.user) do %>
                    <%= attachment_image_tag like.user, :profile_image, fallback: "no-image.jpg", class: "profile_image_icon no-underline" %>
                  <% end %>
                </td>
                <td class="align-middle">
                  <%= link_to user_path(like.user), class: "no-underline" do %>
                    <%= like.user.name %>
                  <% end %>
                </td>
                <td>
                  <% if like.user != current_user %>
                  <!--会員フォローボタン-->
                    <%= render "relationships/follow_button", user: like.user %>
                  <% end %>
                </td>
              </tr>
            <% end %>
        </table>
      <% else %>
        <div>この投稿にいいねした人はいません。</div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_errors.html.erb
<% if post.errors.any? %>
  <div class="alert alert-danger alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-lebel="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <div class="fas fa-exclamation-triangle mb-2 ml-2">
      <span class="font-weight-normal">&thinsp;以下の内容をご確認ください</span>
    </div>
    <div>
      <% post.errors.full_messages.each do |message| %>
        <strong class="ml-3"><%= message %></strong><br />
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/_index.html.erb
<div class="card-deck mx-0 my-3">
  <% posts.each do |post| %>
    <div class="col-md-3 mb-4">
      <div class="card-wrap">
        <div class="card">
          <div class="card-header align-items-center d-flex">
            <%= link_to user_path(post.user), class: "no-underline" do %>
              <%= attachment_image_tag post.user, :profile_image, fallback: "no-image.jpg", class: "profile_image_icon" %>
              <strong class="h5 font-weight-bold"><%= post.user.name %></strong>
            <% end %>
　　　　　　<!--投稿削除ボタン-->
            <% if post.user == current_user %>
              <%= link_to post_path(post), method: :delete, "data-confirm" => "OKを押すと投稿が削除されます。本当によろしいですか？", class: "ml-auto mx-0 my-auto" do %>
                <div class="fas fa-times no-underline-danger lead"></div>
              <% end %>
            <% end %>
          </div>

          <%= link_to post_path(post), data: {"turbolinks" => false}, class: "no-underline" do %>
            <% post.photos.first(1).each do |photo| %>
              <%= attachment_image_tag photo, :image, size:"250x250", class: "d-block mx-auto" %>
            <% end %>
          <% end %>
          <div class="card-body">
            <div>
              <strong class="like-btn_<%= post.id %>">
                <%= render "likes/like-btn", post: post %>
              </strong>
              コメント<%= post.comments.count %>
            </div>
            <div>
              <span><strong><%= truncate post.user.name, length: 8 %></strong></span>
              <span><%= truncate(post.title, length: 9) %></span><br />
              <span><%= truncate(post.caption, length: 18) %></span><br />
              <%= link_to time_ago_in_words(post.created_at, include_seconds: true).upcase + "前", post_path(post), data: {"turbolinks" => false}, class: "post-time no-underline" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
  <div class="mx-auto"><%= paginate @posts %></div>

app/views/posts/edit.html.erb
<div class="topic">
  <div class="container">
    <h1 class="topic-font my-4">投稿編集</h1>
  </div>
</div>
<div class="main">
  <div class="card devise-card">
    <div class="form-wrap">

      <%= render "posts/errors", post: @post %>

  　　<%= form_with model: @post, url: post_path(@post), method: :patch, local:true do |f| %>
        <div class="form-group mb-4">
          <%= f.label "タイトル", class: "font-weight-bold" %>（必須）<br />
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group mb-4">
          <%= f.label "画像", class: "font-weight-bold" %>（必須：最大5枚まで）<br />
          <%= f.attachment_field :photos_images, multiple: true %>
        </div>
        <div class="form-group mb-4">
          <%= f.label "本文", class: "font-weight-bold" %>（必須）<br />
          <%= f.text_area :caption, class: "form-control js-text", rows: 6, placeholder: '例）ゴルフに行きました。天気が良くて気持ちがよかったです。' %>
          <p class="js-text-count text-right mt-1"></p>
        </div>
        <div class="actions">
          <%= f.submit "編集を完了する", class: "btn btn-green w-100" %>
        </div>
      <% end %>

      <div class="mt-3">
        <% if @post.user_id == current_user.id %>
          <%= link_to post_path(@post), method: :delete, "data-confirm" => "OKを押すと投稿が削除されます。本当によろしいですか？" do %>
            <div class="fas fa-trash-alt underline-danger"> 投稿を削除する</div>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="topic">
  <div class="container">
    <div class="row">
      <div class="col">
        <h1 class="topic-font my-4">投稿一覧</h1>
      </div>
      <div class="extra-link my-auto">
        <div class="col d-flex align-items-center justify-content-end">
          <%= link_to rank_posts_path, class: "btn btn-green" do %>
            <div class="fas fa-crown">人気投稿はこちら</div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<p class="text-center my-4">※ 画像をクリックすると、投稿の詳細が見られます。</p>
<%= render 'index', posts: @posts %>

app/views/posts/new.html.erb
<div class="topic">
  <div class="container">
    <h1 class="topic-font my-4">新規投稿</h1>
  </div>
</div>
<div class="main">
  <div class="card devise-card">
    <div class="form-wrap">
      <p class="text-center mb-4">※ 以下のフォームに必要事項を入力してください。</p>

      <%= render "posts/errors", post: @post %>

      <%= form_with model: @post, local: true do |f| %>
        <div class="form-group mb-4">
          <%= f.label "タイトル", class: "font-weight-bold" %>（必須）<br />
          <%= f.text_field :title, class: "form-control", placeholder: '例）ゴルフ' %>
        </div>
        <div class="form-group mb-4">
          <%= f.label "画像", class: "font-weight-bold" %>（必須：最大5枚まで）<br />
          <%= f.attachment_field :photos_images, multiple: true %>
        </div>
        <div class="form-group mb-4">
          <%= f.label "本文", class: "font-weight-bold" %>（必須）<br />
          <%= f.text_area :caption, class: "form-control js-text", rows: 6, placeholder: '例）ゴルフに行きました。天気が良くて気持ちがよかったです。' %>
          <p class="js-text-count text-right mt-1"></p>
        </div>
        <div class="actions">
          <%= f.submit "投稿する", class: "btn btn-green w-100" %>
        </div>
        <div class="my-2 text-center">ボタンを押すと投稿することができます。</div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/rank.html.erb
<div class="topic">
  <div class="container">
    <h1 class="topic-font my-4">人気投稿ランキング</h1>
  </div>
</div>
<%= render 'index', posts: @posts %>

app/views/posts/show.html.erb
<div class="topic">
  <div class="container">
    <h1 class="topic-font my-4">投稿詳細</h1>
  </div>
</div>

<div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap px-0">
    <div class="col-md-7">
      <div class="card-left">
        <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
        <div id="slider">
        <% @post.photos.each do |image| %>
          <%= attachment_image_tag image, :image, class: "card-img-top" %>
        <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-5 px-0">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name">
            <%= link_to user_path(@post.user), class: "no-underline" do %>
              <%= attachment_image_tag @post.user, :profile_image, fallback: "no-image.jpg", class: "profile_image_icon" %>
            <% end %>
            <%= link_to user_path(@post.user), class: "no-underline post-user-name", title: @post.user.name do %>
              <h5 class="mb-0 font-weight-bold"><%= truncate(@post.user.name, length: 8) %></h5>
            <% end %>

        　　<%= render "relationships/follow_button", user: @user %>

            <!--閲覧者がcurrent_userなら投稿編集ページへのボタンを表示-->
            <% if @post.user == current_user %>
              <%= link_to "投稿編集", edit_post_path(@post), class: "btn btn-green btn-md ml-auto mx-0 my-auto" %>
            <% else %>
            <!--閲覧者がcurrent_user以外なら会員詳細ページへのボタンを表示-->
              <%= link_to "会員の詳細", user_path(@post.user), class: "btn btn-green btn-md ml-auto mx-0 my-auto" %>
            <% end %>
          </div>

          <div class="m-2 card-right-title">
            <h5 class="card-title mb-0"><%= @post.title %></h5>
          </div>
          <div class="m-2">
            <%= @post.caption %>
          </div>
          <div class="comments m-2">
            <%= render "comments/comment", post: @post %>
          </div>
        </div>
        <div class="m-2 like-btn_<%= @post.id %>"><%= render "likes/like-btn", post: @post %></div>
        <div class="m-2"><%= link_to "いいね一覧", post_likes_path(@post.id), class: "underline_link" %></div>
        <div class="m-2 post-time"><%= time_ago_in_words(@post.created_at).upcase %>前</div>
        <hr>
        <div class="new-comment">
          <div class="comments-error">
            <%= render "comments/errors", comment: @comment %>
          </div>
          <%= form_with(model:[@post, @comment], remote: true) do |f| %>
            <%= f.text_field :comment, class: "form-control", placeholder: "コメント" %>
            <div class="text-right mt-2"><%= f.submit "送信する", class: "btn btn-green" %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>