config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    get 'confirm_email', to: 'users/registrations#confirm_email'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'homes#top'

  resources :users, except: [:new, :create] do
    member do
      get :following, :followers, :likes
    end
  end

  get 'users/:id/unsubscribe', to: 'users#unsubscribe', as: 'confirm_unsubscribe'

  resources :posts do
    collection do
      get :rank
    end
    resources :photos, only: [:create]
    resources :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :contacts, only: [:new, :create] do
    collection do
      get 'confirm', to: 'contacts#error'
      post 'confirm'
      get 'back', to: 'contacts#error'
      post 'back'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  # いいねランキング用
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  def follow(other_user)
    unless self == other_user
      relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def following(other_user)
    relationships.find_by(follow_id: other_user.id)
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: 'guest') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable, :recoverable,
          :trackable, :rememberable, :validatable, :confirmable

  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 10 }

  validates :profile, length: { maximum: 1000 }

  attachment :profile_image
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: :destroy

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    confirm_email_path
  end

  def confirm_email
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    posts_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def new_guest
    user = User.guest
    sign_in user
    redirect_to posts_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :non_presence_user, except: [:index]

  def index
    @users = User.all.page(params[:page]).reverse_order.per(12)
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
    @user = User.find_by(id: params[:id])
    if @user != current_user || @user == User.guest
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "会員情報を更新しました。"
    else
      render :edit
    end
  end

  def unsubscribe
    @user = User.find_by(id: params[:id])
    if @user != current_user || @user == User.guest
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  def following
    @user = User.find_by(id: params[:id])
    @followings = @user.followings
  end

  def followers
    @user = User.find_by(id: params[:id])
    @followers = @user.followers
  end

  def likes
    @user = User.find_by(id: params[:id])
    likes = Like.where(user_id: @user.id)
    @likes = Kaminari.paginate_array(likes).page(params[:page]).per(12)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :profile, :profile_image)
  end

  def non_presence_user
    @user = User.find_by(id: params[:id])
    if @user.blank?
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.erb
<% if user.errors.any? %>
  <div class="alert alert-danger alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-lebel="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <div class="fas fa-exclamation-triangle mb-2 ml-2">
      <span class="font-weight-normal">&thinsp;以下の内容をご確認ください</span>
    </div>
    <div>
      <% user.errors.full_messages.each do |message| %>
        <strong class="ml-3"><%= message %></strong><br />
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="topic">
  <div class="container">
    <h1 class="topic-font my-4">会員編集</h1>
  </div>
</div>

<div class="main">
  <div class="card devise-card">
    <div class="form-wrap">

    <%= render "users/errors", user: @user %>

　　<%= form_with model: @user, url: user_path(@user), method: :patch, local:true do |f| %>
      <div class="form-group mb-4">
        <%= f.label "お名前", class: "font-weight-bold mb-2" %>（2文字以上10文字以内）<br />
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group mb-4">
        <%= f.label "メールアドレス", class: "font-weight-bold" %>（半角英数字）<br />
        <%= f.email_field :email, class: "form-control" %>
      </div>

      <div class="form-group mb-4">
        <%= f.label :profile_image, "プロフィール画像", class: "font-weight-bold" %>
        <%= f.attachment_field :profile_image, class: "input" %>
      </div>

      <div class="form-group">
        <%= f.label "自己紹介", class: "font-weight-bold" %>（最大1000文字）<br />
        <%= f.text_area :profile, class: "form-control js-text", rows: 6, placeholder: '例）ゴルフが趣味です。ゴルフ友達を募集しています。' %>
        <p class="js-text-count text-right mt-1"></p>
      </div>

      <div class="actions">
        <%= f.submit "編集を完了する", class: "btn btn-green w-100" %>
      </div>
    <% end %>
    <div class="mt-3">退会をご希望の方はこちら → <%= link_to "退会する", confirm_unsubscribe_path(current_user), class: "underline-danger" %></div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="topic">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <h1 class="topic-font my-4">フォロワー</h1>
      </div>
      <div class="col-md-9 my-auto">
        <div><%= @user.name %>さんを、<strong>フォロー</strong>している会員さん一覧です。</div>
      </div>
    </div>
  </div>
</div>
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 mx-auto text-center">
      <% if @followers.present? %>
        <table class="table">
          <tr>
            <th>フォローワー数：<%= @user.followers.count %></th>
            <th>会員名</th>
            <th>フォロー</th>
          </tr>
            <% @followers.each do |follower| %>
              <tr>
                <td class="pt-3">
                  <%= link_to user_path(follower), class: "no-underline" do %>
                    <%= attachment_image_tag follower, :profile_image, fallback: "no-image.jpg", class: "profile_image_icon" %>
                  <% end %>
                </td>
                <td class="align-middle">
                  <%= link_to user_path(follower), class: "no-underline" do %>
                    <%= follower.name %>
                  <% end %>
                </td>
                <td class="pt-1 pb-3">
                  <!--会員フォローボタン-->
                  <%= render "relationships/follow_button", user: follower %>
                </td>
              </tr>
            <% end %>
        </table>
      <% else %>
        <div><%= @user.name %>さんをフォローしている会員はいません。</div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/following.html.erb
<div class="topic">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <h1 class="topic-font my-4">フォロー中</h1>
      </div>
      <div class="col-md-9 my-auto">
        <div><%= @user.name %>さんが、<strong>フォロー</strong>している会員さん一覧です。</div>
      </div>
    </div>
  </div>
</div>
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 mx-auto text-center">
      <% if @followings.present? %>
        <table class="table">
          <tr>
            <th>フォロー数：<%= @user.followings.count %></th>
            <th>会員名</th>
            <th>フォロー</th>
          </tr>
            <% @followings.each do |following| %>
              <tr>
                <td class="pt-3">
                  <%= link_to user_path(following), class: "no-underline" do %>
                    <%= attachment_image_tag following, :profile_image, fallback: "no-image.jpg", class: "profile_image_icon" %>
                  <% end %>
                </td>
                <td class="align-middle">
                  <%= link_to user_path(following), class: "no-underline" do %>
                    <%= following.name %>
                  <% end %>
                </td>
                <td class="pt-2 pb-3">
                  <%= render "relationships/follow_button", user: following %>
                </td>
              </tr>
            <% end %>
        </table>
      <% else %>
        <div><%= @user.name %>さんがフォロー中の会員はいません。</div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="topic">
  <div class="container">
    <h1 class="topic-font my-4">会員一覧</h1>
  </div>
</div>
<p class="text-center my-4">※ 画像をクリックすると、会員様の詳細が見られます。</p>
<div class="card-deck mx-0 my-3">
  <% @users.each do |user| %>
    <div class="col-md-3 mb-4">
      <div class="card-wrap">
        <div class="card">
            <%= link_to user_path(user), class: "no-underline" do %>
              <%= attachment_image_tag user, :profile_image, fallback: "no-image.jpg", size:"250x250", class: "d-block mx-auto" %>
            <% end %>
          <div class="card-body">
            <div>
              <%= link_to user_path(user), class: "no-underline" do %>
                <strong class="h5 font-weight-bold"><%= user.name %></strong>
              <% end %>
              <div><%= truncate(user.profile, length: 30) %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="mx-auto"><%= paginate @users %></div>

app/views/users/likes.html.erb
<div class="topic">
  <div class="container">
    <h1 class="topic-font my-4"><%= @user.name %>さんがいいねした投稿</h1>
  </div>
</div>
<% if @likes.present? %>
  <div class="card-deck mx-0 my-3">
    <% @likes.each do |like| %>
      <% post = Post.find_by(id: like.post_id ) do %>
      <% end %>
      <div class="col-md-3 mb-4">
        <div class="card-wrap">
          <div class="card">
            <div class="card-header align-items-center d-flex">
              <%= link_to user_path(post.user), class: "no-underline" do %>
                <%= attachment_image_tag post.user, :profile_image, fallback: "no-image.jpg", class: "profile_image_icon" %>
                <strong class="h5 font-weight-bold"><%= post.user.name %></strong>
              <% end %>
              <!--投稿削除ボタン-->
              <% if post.user == current_user %>
                <%= link_to post_path(post), method: :delete, "data-confirm" => "OKを押すと投稿が削除されます。本当によろしいですか？", class: "ml-auto mx-0 my-auto" do %>
                  <div class="fas fa-times no-underline-danger lead"></div>
                <% end %>
              <% end %>
            </div>

            <%= link_to post_path(post), data: {"turbolinks" => false}, class: "no-underline" do %>
              <% post.photos.first(1).each do |photo| %>
                <%= attachment_image_tag photo, :image, size:"250x250", class: "d-block mx-auto" %>
              <% end %>
            <% end %>
            <div class="card-body">
              <div>
                <strong class="like-btn_<%= post.id %>">
                  <%= render "likes/like-btn", post: post %>
                </strong>
                コメント<%= post.comments.count %>
              </div>
              <div>
                <span><strong><%= truncate post.user.name, length: 8 %></strong></span>
                <span><%= truncate(post.title, length: 9) %></span><br />
                <span><%= truncate(post.caption, length: 18) %></span><br />
                <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), data: {"turbolinks" => false}, class: "post-time no-underline" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="text-center mt-5"><%= @user.name %>さんがいいねした投稿はありません。</div>
<% end %>
<div class="mx-auto">
  <%= paginate @likes %>
</div>

app/views/users/show.html.erb
<div class="topic">
  <div class="container">
    <div class="row">
      <div class="col">
        <h1 class="topic-font my-4">会員詳細</h1>
      </div>
      <div class="extra-link my-auto">
        <div class="col d-flex align-items-center justify-content-end">
          <% if current_user == @user %>
            <%= link_to "会員情報の編集", edit_user_path(@user), class: "btn btn-green" %>
          <% else %>
            <%= link_to chat_path(@user), class: "btn btn-green" do %>
              <div class="fas fa-comments">&nbsp;<%= @user.name %>さんとチャットする</div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="my-5">
    <div class="row">
      <div class="col-md-3 text-center">
        <%= attachment_image_tag @user, :profile_image, fallback: "no-image.jpg", size:"120x120", class: "rounded-circle" %>
      </div>
      <div class="col-md-9 pr-0">
        <div class="row mb-3">
          <div class="col-md-4 my-auto">
            <h4 class="font-weight-bold"><%= @user.name %></h4>
          </div>
          <% if @user == current_user %>
            <div class="col-md-4">
              <p class="font-weight-bold mail-font"><%= truncate @user.email, length: 25 %></p>
            </div>
          <% else %>
            <div class="col-md-8">
            <!--会員フォローボタン-->
        　　<%= render "relationships/follow_button", user: @user %>
        　　</div>
          <% end %>
        </div>
        <div class="row">
          <div class="col-md-2">
            投稿&nbsp;<strong><%= @user.posts.count %></strong>件
          </div>
          <div class="col-md-4">
            <%= link_to likes_user_path(@user), class: "underline_link" do %>
              いいねした投稿&nbsp;<strong><%= @user.likes.count %></strong>件
            <% end %>
          </div>
          <div class="col-md-3">
            <%= link_to followers_user_path(@user), class: "underline_link" do %>
              フォロワー&nbsp;<strong id="followers-count"><%= @user.followers.count %></strong>人
            <% end %>
          </div>
          <div class="col-md-3">
            <%= link_to following_user_path(@user), class: "underline_link" do %>
              フォロー中&nbsp;<strong><%= @user.followings.count %></strong>人
            <% end %>
          </div>
        </div>
        <div class="mt-4 mr-5"><%= @user.profile %></div>
      </div>
    </div>
  </div>
</div>
<div class="card-deck mx-0 mb-3">
  <% @user.posts.each do |post| %>
    <div class="col-lg-3 mt-3">
      <div class="card-wrap">
        <div class="card">
          <div class="card-header align-items-center d-flex">
            <!--投稿削除ボタン-->
            <% if post.user_id == current_user.id %>
              <%= link_to post_path(post), method: :delete, "data-confirm" => "OKを押すと投稿が削除されます。本当によろしいですか？", class: "ml-auto mx-0 my-auto" do %>
                <div class="fas fa-times no-underline-danger lead"></div>
              <% end %>
            <% end %>
          </div>
          <%= link_to post_path(post), data: {"turbolinks" => false}, class: "no-underline" do %>
            <% post.photos.first(1).each do |photo| %>
              <%= attachment_image_tag photo, :image, size:"250x250", class: "d-block mx-auto" %>
            <% end %>
          <% end %>
          <div class="card-body">
            <div class="like-btn_<%= post.id %>"><%= render "likes/like-btn", post: post %></div>
            <div>
              <span><strong><%= truncate post.user.name, length: 8 %></strong></span>
              <span><%= truncate(post.title, length: 9) %></span><br />
              <span><%= truncate(post.caption, length: 18) %></span><br />
              <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), class: "post-time no-underline" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/unsubscribe.html.erb
<div class="topic">
  <div class="container">
    <h1 class="topic-font my-4">退会</h1>
  </div>
</div>

<div class="main">
  <div class="card border-danger">
    <div class="card-header bg-danger"><h2 class="text-center mb-0"><span class="text-light">ご注意ください</span></h2></div>
    <div class="form-wrap-danger">
      <p class="pl-1">こちらは<strong>おばコミュ</strong>から退会するためのページです。<br />
         おばコミュから退会手続きを完了しますと<br />
         <span class="text-danger font-weight-bold">退会した会員を再度利用することはできなくなります。</span>
      </p>
      <div class="text-center mt-4">
        <%= link_to "マイページに戻る", user_path(current_user), class: "btn btn-green mr-2 btn-lg" %>
        <%= link_to "退会する", user_path(current_user), method: :delete, "data-confirm" => "OKを押すと退会処理がされます。本当によろしいですか？", class: "btn btn-danger btn-shadow btn-lg" %>
    	</div>
    </div>
  </div>
</div>