config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    get 'confirm_email', to: 'users/registrations#confirm_email'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'homes#top'

  resources :users, except: [:new, :create] do
    member do
      get :following, :followers, :likes
    end
  end

  get 'users/:id/unsubscribe', to: 'users#unsubscribe', as: 'confirm_unsubscribe'

  resources :posts do
    collection do
      get :rank
    end
    resources :photos, only: [:create]
    resources :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :contacts, only: [:new, :create] do
    collection do
      get 'confirm', to: 'contacts#error'
      post 'confirm'
      get 'back', to: 'contacts#error'
      post 'back'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 100 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post

  attachment :image

  validates :image, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  # いいねランキング用
  has_many :liked_users, through: :likes, source: :user
  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_attachments_for :photos, attachment: :image
  validates :title, presence: true
  validates :caption, presence: true, length: { maximum: 1000 }
  validates :photos_images, presence: true, length: { maximum: 5, too_long: "は最大%{count}枚まで投稿できます" }

  def liked_by(user)
    # user_idとpost_idが一致するlikeを検索する
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  # いいねランキング用
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  def follow(other_user)
    unless self == other_user
      relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def following(other_user)
    relationships.find_by(follow_id: other_user.id)
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: 'guest') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable, :recoverable,
          :trackable, :rememberable, :validatable, :confirmable

  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 10 }

  validates :profile, length: { maximum: 1000 }

  attachment :profile_image
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :non_presence_chat, except: [:create]

  def show
    @user = User.find_by(id: params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    if user_rooms.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    else
      @room = user_rooms.room
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
    redirect_to request.referer
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

  def non_presence_chat
    @user = User.find_by(id: params[:id])
    if @user.blank?
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  # お問い合わせ内容確認画面
  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end

  # 入力内容変更
  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  # ブラウザバック時のエラー対応用
  def error
    redirect_to new_contact_path
  end

  # 送信するアクション
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to posts_path, notice: "お問い合わせ内容を送信しました。"
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :name, :message)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @posts = Post.all.order('created_at DESC').limit(3)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def index
    @post_for_likes = Like.where(post_id: params[:post_id])
    @post = Post.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    like = current_user.likes.new(post_id: @post.id)
    like.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_errors.html.erb
<% if contact.errors.any? %>
  <div class="alert alert-danger alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-lebel="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <div class="fas fa-exclamation-triangle mb-2 ml-2">
      <span class="font-weight-normal">&thinsp;以下の内容をご確認ください</span>
    </div>
    <div>
      <% contact.errors.full_messages.each do |message| %>
        <strong class="ml-3"><%= message %></strong><br />
      <% end %>
    </div>
  </div>
<% end %>

app/views/contacts/confirm.html.erb
<div class="topic">
  <div class="container">
    <h1 class="topic-font my-4">お問い合わせ内容確認</h1>
  </div>
</div>

<div class="main">
  <div class="card devise-card">
    <div class="form-wrap">
      <div class="form-group mb-0">
        <h3 class="mx-auto text-center">お問い合わせ内容</h3>
        <p class="text-center mt-3">
          内容はこちらでお間違いないでしょうか？<br />
          よろしければ【送信する】ボタンを押してください。<br />
          48時間以内にメールにて回答いたします。
        </p>
        <table class="table table-bordered table-condensed">
          <tbody>
            <tr>
              <td>お名前</td>
              <td class="text-left"><%= @contact.name %></td>
            </tr>
            <tr>
              <td>メールアドレス</td>
              <td><%= @contact.email %></td>
            </tr>
            <tr>
              <td>お問い合わせ内容</td>
              <td style="white-space: pre-wrap;"><%= @contact.message %></td>
            </tr>
          </tbody>
        </table>

        <div class="text-center mt-4">
          <%= form_with model: @contact, local: true do |f| %>
            <%= f.hidden_field :name %>
            <%= f.hidden_field :email %>
            <%= f.hidden_field :message %>
            <%= f.submit '送信する', class: "btn btn-green w-100" %>
          <% end %>
          <%= form_with model: @contact, url: back_contacts_path, local: true do |f| %>
            <%= f.hidden_field :name %>
            <%= f.hidden_field :email %>
            <%= f.hidden_field :message %>
            <div class="mt-3">内容変更はこちら→ <%= f.submit '入力画面に戻る', class: "btn btn-link p-0" %></div>
          <% end %>
        </div>
      </div>
　  </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="topic">
  <div class="container">
    <h1 class="topic-font my-4">お問い合わせ</h1>
  </div>
</div>

<div class="main">
  <div class="card devise-card">
    <div class="form-wrap">
      <div class="form-group mb-4">
        <h3 class="mx-auto text-center">お問い合わせフォーム</h3>
        <p class="mt-3">お問い合わせ内容を以下のフォームにご入力ください。</p>
        <p>
          *回答は全てメールで返信させていただきます。<br />
          <span class="text-danger">ご入力いただいたメールアドレスが正しくない場合は、返信のメールが届きません。</span><br />
          お間違えのないようにご入力ください。
        </p>
      </div>
      <%= form_with model: @contact, url: confirm_contacts_path, local:true do |f| %>

        <%= render "contacts/errors", contact: @contact %>

        <div class="form-group">
          <%= f.label :name, 'お名前*' %>
          <%= f.text_field :name, autofocus: true, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :email, 'メールアドレス*' %><br />
          <%= f.email_field :email, autofocus: true, placeholder: "例) example@example.com", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :message, 'お問い合わせ内容*' %>
          <%= f.text_area :message, size: '10x10', placeholder: "例）ログインできないのですが、どのようにしたらよいのでしょうか？", class: 'form-control' %>
        </div>

        <div>
          <%= f.submit '入力内容確認', class: "btn btn-green w-100" %>
        </div>
      <% end %>
    </div>
  </div>
</div>