config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    get 'confirm_email', to: 'users/registrations#confirm_email'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'homes#top'

  resources :users, except: [:new, :create] do
    member do
      get :following, :followers, :likes
    end
  end

  get 'users/:id/unsubscribe', to: 'users#unsubscribe', as: 'confirm_unsubscribe'

  resources :posts do
    collection do
      get :rank
    end
    resources :photos, only: [:create]
    resources :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :contacts, only: [:new, :create] do
    collection do
      get 'confirm', to: 'contacts#error'
      post 'confirm'
      get 'back', to: 'contacts#error'
      post 'back'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 100 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post

  attachment :image

  validates :image, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  # いいねランキング用
  has_many :liked_users, through: :likes, source: :user
  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_attachments_for :photos, attachment: :image
  validates :title, presence: true
  validates :caption, presence: true, length: { maximum: 1000 }
  validates :photos_images, presence: true, length: { maximum: 5, too_long: "は最大%{count}枚まで投稿できます" }

  def liked_by(user)
    # user_idとpost_idが一致するlikeを検索する
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  # いいねランキング用
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  def follow(other_user)
    unless self == other_user
      relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def following(other_user)
    relationships.find_by(follow_id: other_user.id)
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: 'guest') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable, :recoverable,
          :trackable, :rememberable, :validatable, :confirmable

  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 10 }

  validates :profile, length: { maximum: 1000 }

  attachment :profile_image
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :non_presence_chat, except: [:create]

  def show
    @user = User.find_by(id: params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    if user_rooms.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    else
      @room = user_rooms.room
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
    redirect_to request.referer
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

  def non_presence_chat
    @user = User.find_by(id: params[:id])
    if @user.blank?
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if comment.errors.any? %>
  <div id="error_explanation" class="alert alert-danger alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-lebel="Close">
      <span aria-hidden="true">&times;</span>
    </button>
      <% comment.errors.full_messages.each do |message| %>
        <strong class="fas fa-exclamation-triangle ml-4">&nbsp;<%= message %></strong>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center">
      <p class="mt-3">
        Copyright © ObaCommu
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <% if user_signed_in? %>
        <a class="logo-img" href="/posts"><%= image_tag('logo.png')%></a>
    <% else %>
        <a class="logo-img" href="/"><%= image_tag('logo.png')%></a>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-md-auto align-items-center font-weight-bold">
        <% if user_signed_in? %>
          <!--検索フォーム（投稿タイトル）-->
          <li>
            <%= search_form_for @search, url: posts_path, class: "form-inline" do |f| %>
              <div class="input-group">
                <%= f.search_field :title_cont, placeholder: "タイトル", class: "form-control search-form-with" %>
                <span class="input-group-btn">
                  <%= f.submit '検索', class: "btn btn-secondary mr-2 py-2" %>
                </span>
              </div>
            <% end %>
          </li>
          <li><%= link_to "投稿する", new_post_path, class: "nav-link text-light" %></li>
          <li><%= link_to "マイページ", user_path(current_user), class: "nav-link text-light" %></li>
          <li><%= link_to "会員一覧", users_path, class: "nav-link text-light" %></li>
          <li><%= link_to "投稿一覧", posts_path, class: "nav-link text-light" %></li>
          <li><%= link_to "お問い合わせ", new_contact_path, class: "nav-link text-light" %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link text-light" %></li>
        <% else %>
          <li><%= link_to "トップページ", root_path, class: "nav-link text-light" %></li>
          <li><%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "nav-link text-light" %></li>
          <li><%= link_to "会員登録", new_user_registration_path, class: "nav-link text-light" %></li>
          <li><%= link_to "ログイン", new_user_session_path, class: "nav-link text-light", id: "log-in" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ObaCommu</title>
    <!--posts/show.html.erb 画像スライダー-->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <!--ここまで-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>

    <div id="wrapper">
      <%= render 'layouts/header' %>

      <% if flash[:notice] %>
        <div class="alert alert-info mb-0">
          <button type="button" class="close" data-dismiss="alert" aria-lebel="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:alert] %>
        <div class="alert alert-danger mb-0">
          <button type="button" class="close" data-dismiss="alert" aria-lebel="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>

    </div>

  </body>
</html>